### ISSUE TITLE
cant craft more than 1 item (addon error)

### ISSUE THREAD

**Issue by nukhub** [TLDRMissions/FixCraftingOrdersDisconnect#1]
1x [ADDON_ACTION_BLOCKED] L'AddOn 'FixCraftingOrdersDisconnect' a tenté d'appeler la fonction protégée 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `CraftRecipe'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:769: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:768>
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:828: in function `craftingCallback'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:713: in function `ContinueCrafting'
[string "@Blizzard_Professions/Blizzard_ProfessionsCrafting.lua"]:128: in function <...lizzard_Professions/Blizzard_ProfessionsCrafting.lua:120>

small isssue, thanks for this, i was going crazy without it

**Comment by teelolws** [comment]
The bug has finally been fixed by Blizz. You can uninstall this now!
